os: linux
dist: focal

language: java
jdk: openjdk11

branches:
  only:
  # We run tests on Jenkins for the main branch, so let's have Travis only in place for 2.5.x
    - 2.5.x
    
cache:
  directories:
  - $HOME/.m2

before_cache:
  # remove resolver-status.properties, they change with each run and invalidate the cache
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

notifications:
    webhooks: https://www.travisbuddy.com/

travisBuddy:
    insertMode: update
    successBuildLog: true

install: true
script: ./buildci.sh "$TRAVIS_COMMIT_RANGE"
